[package]
name = "git-sync"
edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
serde = { version = "1", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }

toml = "0.8.20"
execute = "0.2.13"
