[package]
name = "git-sync"
edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
serde = { version = "*", features = ["derive"] }
clap = { version = "*", features = ["derive"] }

toml = "0.8.19"


execute = "0.2.13"
