services:
  mirror:
    build: .
    volumes:
      - "./docker-config/config.toml:/root/config.toml"
      - "./docker-config/github:/root/.ssh/id_rsa:ro"
      - "./docker-config/github.pub:/root/.ssh/id_rsa.pub:ro"
      - "./docker-config/known_hosts:/root/.ssh/known_hosts"
    networks:
      internet:

networks:
  internet:
